"use client";
/* eslint-disable react/no-unescaped-entities */

import { useEffect, useMemo, useState, type ReactNode } from "react";

type GuideSection = { id: string; title: string; search: string; content: ReactNode };

const sections: GuideSection[] = [
  { id: "hizli-baslangic", title: "1. Hızlı Başlangıç", search: "başlangıç prompt hazır görsel yükle ürün oda mockup indir", content: <><p>Ana sayfada iki başlangıç yolu bulunur:</p><ol><li><b>Prompt Oluştur:</b> Tema, stil, palet ve motif seçimlerinden İngilizce Midjourney promptu hazırlayın; ürettiğiniz sonucu uygulamaya yükleyin.</li><li><b>Hazır Görsel Yükle:</b> Prompt oluşturmadan elinizdeki JPG, PNG veya WEBP dosyasıyla doğrudan başlayın.</li></ol><p>Her iki yol da görsel yüklendikten sonra aynı akışta birleşir: <b>Görsel → Mockup Ayarları → Onay → Sonuçlar.</b></p></> },
  { id: "proje-olusturma", title: "2. Proje Oluşturma", search: "project name otomatik proje adı optional internal name", content: <><h3>Proje ne zaman oluşur?</h3><p>İlk görseli yüklediğiniz anda sistem otomatik olarak bir proje oluşturur. Başlangıç ekranında proje adı yazmanız gerekmez.</p><p>Otomatik ad örneği: <b>Wallpaper Project — 17 Sep 2026 — 001</b>.</p><h3>Project Name ne işe yarar?</h3><p>Proje adı yalnızca kendi çalışmalarınızı ayırt etmeniz içindir. <b>Projelerim</b> ekranındaki kalem simgesiyle değiştirebilirsiniz. Etsy başlığına, açıklamasına, etiketlerine veya müşteriye görünen başka bir alana aktarılmaz.</p><h3>Primary Room ve Secondary Room</h3><p><b>Primary Room</b> zorunlu ana mockup kategorisidir. <b>Secondary Room</b> ek çeşitlilik sağlar ve seçilmesi zorunlu değildir.</p></> },
  { id: "gorsel-yukleme", title: "3. Görsel Yükleme", search: "görsel yükleme jpg png webp çözünürlük prompt kaynak değişmez", content: <><p>Kendi hazırladığınız duvar kâğıdı görselini doğrudan yükleyebilirsiniz. Prompt Studio kullanmak zorunlu değildir.</p><ul><li>Desteklenen türler: JPG, PNG ve WEBP.</li><li>Yüksek çözünürlüklü görseller daha temiz sonuç verir.</li><li>Düşük çözünürlük uyarısı, 3000 × 3000 mockuplarda detay kaybı oluşabileceğini belirtir.</li><li>Kaynak görsel, temiz interior scene ile birlikte FLUX.2 Pro Edit'e orijinal wallpaper referansı olarak gönderilir.</li></ul><div className="guide-note">Kaynak dosyanız ile mockup çıktıları ayrı tutulur. Bir mockupı yenilemek kaynak görseli değiştirmez.</div></> },
  { id: "seamless-pattern", title: "4. Seamless Pattern Nedir?", search: "seamless pattern scale small medium large tekrar desen", content: <><p>Seamless Pattern, kenarları birbirine uyumlu şekilde tekrar edebilen desen tasarımıdır. Görsel, mockup duvarına tekrar edilerek uygulanır.</p><dl><div><dt>Small</dt><dd>Desen daha küçük ve daha sık tekrar eder.</dd></div><div><dt>Medium</dt><dd>Dengeli bir desen büyüklüğü sağlar.</dd></div><div><dt>Large</dt><dd>Deseni daha büyük ve dikkat çekici gösterir.</dd></div></dl><div className="guide-note"><b>Önemli:</b> Pattern Scale gerçek baskı veya duvar ölçüsü değildir. Yalnızca mockuptaki görsel tekrar ölçeğini belirler.</div></> },
  { id: "custom-mural", title: "5. Custom Mural Nedir?", search: "custom mural smart fit show full artwork fill wall focal point width height esnetme", content: <><p>Custom Mural, tek bir kompozisyonun duvar yüzeyine panoramik olarak uygulandığı tasarım türüdür.</p><ul><li>Width veya Height girmeniz gerekmez.</li><li>Sistem görselin en-boy oranını otomatik algılar.</li><li>Görsel orantısız şekilde esnetilmez.</li></ul><h3>Yerleşim seçenekleri</h3><dl><div><dt>Smart Fit</dt><dd>Görseli duvarı dolduracak şekilde dengeli kırpar. Varsayılan ve önerilen seçimdir.</dd></div><div><dt>Show Full Artwork</dt><dd>Kompozisyonun tamamını gösterir; duvar kenarlarında boşluk kalabilir.</dd></div><div><dt>Fill Wall</dt><dd>Duvar yüzeyini tamamen doldurur; kenarlardan kontrollü kırpma yapabilir.</dd></div><div><dt>Focal Point</dt><dd>Önemli bölgeyi önizleme üzerinde sürükleyerek seçmenizi sağlar. Kırpma bu noktayı korur.</dd></div></dl></> },
  { id: "oda-kategorileri", title: "6. Oda Kategorisi Seçimi", search: "oda primary secondary nursery kids office gaming bedroom living room dark interior", content: <><p>Primary Room ana mockup kategorisidir. Secondary Room isteğe bağlıdır ve ikinci bir oda görünümüyle çeşitlilik sağlar.</p><ul><li>Çocuk desenleri: Nursery veya Kids Room</li><li>Kurumsal desenler: Office / Studio</li><li>Koyu ve modern desenler: Gaming Room veya koyu iç mekân</li><li>Zarif ve sakin desenler: Bedroom</li><li>Genel dekoratif desenler: Living Room</li></ul><p>Desenin tarzına uygun oda seçmek daha doğal ve satılabilir sonuçlar verir.</p></> },
  { id: "mockup-olusturma", title: "7. Mockup Oluşturma", search: "onay generate mockups altı 6 fal kredi ilerleme", content: <><p>Mockup Ayarları'ndan sonra <b>Onay</b> ekranı açılır. Burada kaynak görseli, ürün türünü, oda seçimlerini, ölçek veya yerleşimi, altı mockup sayısını ve bağlantı durumunu kontrol edersiniz.</p><p><b>6 Mockup Oluştur</b> düğmesi altı bağımsız işi yalnızca bir kez başlatır.</p><ul><li>Her mockupın durumu Bekliyor, Oluşturuluyor, Tamamlandı veya Başarısız olarak izlenir.</li><li>Tamamlanan görsel onaylanabilir veya reddedilebilir.</li><li>Yalnızca başarısız ya da reddedilmiş slot yeniden oluşturulabilir.</li><li>Onaylanan görseller tek ZIP paketi olarak indirilebilir.</li></ul></> },
  { id: "fal-ai", title: "8. Fal.ai Bağlantısı ve Kredi Kullanımı", search: "fal.ai fal api key anahtar kredi bakiye etsy okulu backend bağlantı", content: <><p>Gerçek üretimde bağlantı Etsy Okulu hesabınız üzerinden sunucu tarafında yönetilir. Tarayıcıda API anahtarı alanı gösterilmez.</p><ol><li>Etsy Okulu hesabınızda Fal.ai bağlantısını güvenli bağlantılar bölümünden kurarsınız.</li><li>Anahtar şifreli biçimde sunucuda saklanır.</li><li>Wallpaper AI Studio üretim isteğini giriş yaptığınız kullanıcı hesabıyla sunucuya gönderir.</li><li>Maliyet kendi Fal.ai bakiyenizden düşer.</li><li>Tarayıcıya yalnızca iş numarası, durum ve güvenli çıktı adresleri döner.</li></ol><div className="guide-note"><b>Demo Mode — Real Fal.ai generation is not connected</b> mesajını görüyorsanız uygulama yalnızca yerel örnek çıktı üretir. Bu çıktılar gerçek Fal.ai sonucu değildir. API anahtarını sohbette paylaşmayın; URL'ye, tarayıcı depolamasına veya istemci koduna eklemeyin.</div></> },
  { id: "mockup-inceleme", title: "9. Mockupları İnceleme", search: "mockup büyük görüntüle approve reject regenerate download selected zip onay reddet yenile indir", content: <><ul><li>Önizlemeye tıklayarak mockupı büyük görüntüleyin.</li><li><b>Approve</b> ile kullanılacak görseli onaylayın.</li><li><b>Reject</b> ile uygun olmayan görseli işaretleyin.</li><li><b>Regenerate</b> ile yalnızca o mockupı yeniden üretin.</li><li><b>Download</b> ile tek bir görseli indirin.</li><li>Kutucukları seçip <b>Download selected ZIP</b> ile seçilenleri indirin.</li><li><b>ZIP all approved</b> ile tüm onaylananları tek pakete alın.</li></ul></> },
  { id: "hata-durumlari", title: "10. Hata Durumları", search: "hata fal bağlantı kredi yüklenemedi format çözünürlük başarısız uzun zip", content: <><dl><div><dt>Fal.ai bağlantısı bulunamadı</dt><dd>Etsy Okulu hesabınızdaki Fal.ai bağlantı durumunu kontrol edin. Anahtarı Wallpaper AI Studio ekranına yazmayın.</dd></div><div><dt>Yetersiz kredi</dt><dd>Fal.ai hesabınıza bakiye ekleyin, ardından yalnızca başarısız slotu yenileyin.</dd></div><div><dt>Görsel yüklenemedi</dt><dd>Dosyanın bozuk olmadığını ve tarayıcı tarafından açılabildiğini kontrol edin.</dd></div><div><dt>Desteklenmeyen dosya türü</dt><dd>Görseli JPG, PNG veya WEBP olarak dışa aktarın.</dd></div><div><dt>Çözünürlük düşük</dt><dd>Daha büyük piksel ölçüsüne sahip kaynak dosya yükleyin.</dd></div><div><dt>Mockup üretimi başarısız</dt><dd>İlgili slotta Regenerate düğmesini kullanın.</dd></div><div><dt>Üretim uzun sürüyor</dt><dd>Bağlantınızı kontrol edin; iş durumu değişmiyorsa sayfayı yenilemeden birkaç dakika bekleyin.</dd></div><div><dt>ZIP indirilemiyor</dt><dd>En az bir mockupı onaylayın, açılır pencere/indirme iznini kontrol edin ve tekrar deneyin.</dd></div></dl></> },
  { id: "sss", title: "11. Sık Sorulan Sorular", search: "sss duvar ölçüsü etsy varyasyon prompt kendi görsel seamless mural scale kaç kredi zip proje adı", content: <><dl><div><dt>Gerçek duvar ölçüsü girmem gerekiyor mu?</dt><dd>Hayır. Mockup üretimi için gerçek duvar ölçüsü gerekmez.</dd></div><div><dt>Etsy'deki ürün varyasyonlarını buraya eklemeli miyim?</dt><dd>Hayır. Etsy varyasyonları bu uygulamada yönetilmez.</dd></div><div><dt>Prompt oluşturmak zorunda mıyım?</dt><dd>Hayır. Kendi görselinizi doğrudan yükleyebilirsiniz.</dd></div><div><dt>Seamless Pattern ve Custom Mural arasındaki fark nedir?</dt><dd>Seamless tasarım tekrar eder; mural tek panoramik kompozisyondur.</dd></div><div><dt>Pattern Scale gerçek baskı ölçüsü müdür?</dt><dd>Hayır, yalnızca mockuptaki görsel tekrar ölçeğidir.</dd></div><div><dt>Kaç adet mockup oluşturulur?</dt><dd>Varsayılan olarak altı bağımsız mockup oluşturulur.</dd></div><div><dt>Mockupları yeniden üretebilir miyim?</dt><dd>Evet. Her slot ayrı ayrı yenilenebilir.</dd></div><div><dt>Fal.ai kredisi kimden düşer?</dt><dd>Kendi Fal.ai hesabınızdan düşer.</dd></div><div><dt>Görsellerimi ZIP olarak indirebilir miyim?</dt><dd>Evet; seçilen veya tüm onaylanan görselleri ZIP olarak indirebilirsiniz.</dd></div><div><dt>Proje adı Etsy müşterilerine görünür mü?</dt><dd>Hayır. Yalnızca kendi organizasyonunuz içindir.</dd></div></dl></> },
  { id: "gizlilik", title: "12. Gizlilik ve Güvenlik", search: "gizlilik güvenlik api anahtarı zip görseller proje sil hassas", content: <><ul><li>Fal.ai API anahtarı yalnızca sunucu tarafındaki şifreli Secrets alanında tutulmalıdır.</li><li>API anahtarı ZIP dosyasına veya proje metadata dosyalarına eklenmez.</li><li>Yüklenen görseller yalnızca QA, mockup üretimi ve seçtiğiniz dışa aktarma işlemleri için kullanılır.</li><li>Projelerinizi proje menüsündeki silme seçeneği kullanılabilir olduğunda kaldırabilirsiniz.</li><li>API anahtarı, kişisel bilgi veya başka hassas verileri mesajlarda paylaşmayın.</li></ul></> },
];

export function HelpGuide({ open, initialSection, onClose }: { open: boolean; initialSection: string | null; onClose: () => void }) {
  const [query, setQuery] = useState("");
  const visible = useMemo(() => { const needle = query.trim().toLocaleLowerCase("tr-TR"); return needle ? sections.filter((section) => `${section.title} ${section.search}`.toLocaleLowerCase("tr-TR").includes(needle)) : sections; }, [query]);
  useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", onKey); const timer = window.setTimeout(() => document.getElementById(`guide-${initialSection || "hizli-baslangic"}`)?.scrollIntoView({ block: "start" }), 60); return () => { window.removeEventListener("keydown", onKey); window.clearTimeout(timer); }; }, [open, initialSection, onClose]);
  return <><button className={`help-scrim ${open ? "open" : ""}`} aria-label="Kullanım kılavuzunu kapat" tabIndex={open ? 0 : -1} onClick={onClose} /><aside className={`help-drawer ${open ? "open" : ""}`} role="dialog" aria-modal="true" aria-label="Wallpaper AI Studio Kullanım Kılavuzu" aria-hidden={!open}><header><div><span>YARDIM MERKEZİ</span><h2>Wallpaper AI Studio<br />Kullanım Kılavuzu</h2></div><button aria-label="Kullanım kılavuzunu kapat" onClick={onClose}>×</button></header><div className="guide-scroll"><p className="guide-intro">Wallpaper AI Studio, yüklediğiniz duvar kâğıdı tasarımını seçtiğiniz oda kategorilerine göre gerçekçi pazarlama mockuplarına dönüştürmenizi sağlar. Uygulamayı kullanmak için teknik bilgiye veya gerçek duvar ölçülerine ihtiyacınız yoktur.</p><label className="guide-search"><span>KILAVUZDA ARA</span><input type="search" value={query} placeholder="Mural, Fal.ai veya ZIP ara…" onChange={(event) => setQuery(event.target.value)} /></label>{!query && <nav className="guide-toc" aria-label="Kılavuz içindekiler"><span>İÇİNDEKİLER</span>{sections.map((section) => <a key={section.id} href={`#guide-${section.id}`}>{section.title}</a>)}</nav>}<div className="guide-sections">{visible.map((section) => <section key={section.id} id={`guide-${section.id}`}><span>{section.title.split(".")[0].padStart(2, "0")}</span><h2>{section.title.replace(/^\d+\.\s*/, "")}</h2>{section.content}<div className="guide-media-slot" aria-hidden="true">Bu alana açıklayıcı ekran görüntüsü veya şema eklenebilir.</div></section>)}{visible.length === 0 && <div className="guide-empty"><b>Sonuç bulunamadı.</b><p>Başka bir kelime deneyin veya arama alanını temizleyin.</p></div>}</div></div></aside></>;
}
