"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { MockEtsyAdapter } from "../integrations/etsy/index.ts";
import { ZipExportAdapter } from "../integrations/export/index.ts";
import { changeProductType, createDemoProject, refreshProjectName, setPatternScale, updateMeasurements, validateProject } from "../lib/core/project.ts";
import { compilePrompt } from "../lib/core/prompt.ts";
import type { PatternScale, ProductType, Project, PromptSpec } from "../lib/core/types.ts";

const STORAGE_KEY = "wallpaper-ai-studio-demo-v1";
const DEMO_USER_ID = "demo-user";
const marketplace = new MockEtsyAdapter();
const exporter = new ZipExportAdapter();
const steps = [
  ["01", "Project", "Product & room"], ["02", "Prompt Studio", "Creative direction"], ["03", "Design Master", "Upload & print QA"],
  ["04", "Art Direction", "Collection & mood"], ["05", "Render Queue", "Six mockup roles"], ["06", "Listing Studio", "Export or draft"],
] as const;
const rooms = ["Nursery", "Kids Room", "Living Room", "Bedroom", "Gaming Room", "Office / Studio", "Bathroom", "Dining / Entryway"];
const themes = ["Woodland", "Botanical", "Dark Floral", "Pink Bows", "Celestial", "Coastal", "Geometric", "Neon Gaming"];
const styles = ["Hand-painted gouache", "Watercolor", "Engraved", "Vintage textile", "Minimal line art", "Painterly editorial"];
const palettes = ["Warm woodland", "Dusty rose & sage", "Midnight jewel", "Coastal mineral", "Soft neutral", "Sun-washed terracotta"];
const collections = ["Baby & Nursery", "Kids Room", "Living Room", "Bedroom", "Gaming Room", "Dark & Moody", "General Editorial"];
const moods = ["Soft & airy", "Warm neutral", "Playful", "Cinematic", "Organic elegant", "Romantic", "Clean refined"];

function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; placeholder?: string }) {
  return <label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>;
}

function Select({ label, value, values, onChange }: { label: string; value: string; values: readonly string[]; onChange: (value: string) => void }) {
  return <label className="field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item) => <option key={item}>{item}</option>)}</select></label>;
}

function StepTitle({ number, eyebrow, title, copy }: { number: string; eyebrow: string; title: string; copy: string }) {
  return <header className="step-title"><b>{number}</b><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></header>;
}

function ProductStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  const [editing, setEditing] = useState(false);
  const errors = validateProject(project);
  const canContinue = Object.keys(errors).length === 0;
  const masterTags = project.productType === "seamless" ? ["Wall-only artwork", "Seamless repeat", "1:1 master", "No furniture", "No staging", "No perspective"] : ["Wall-only artwork", "Custom ratio", "Panoramic master", "Edge-safe", "No furniture", "No perspective"];
  const setRoom = (key: "primaryTargetRoom" | "secondaryTargetRoom", value: string) => update(key === "primaryTargetRoom" ? refreshProjectName({ ...project, [key]: value }) : { ...project, [key]: value });
  return <section className="stage">
    <StepTitle number="01" eyebrow="NEW PROJECT" title="Start with one source of truth." copy="Everything works in demo mode before a marketplace is connected." />
    <div className="paper-card form-card">
      <div className="project-name"><div><span>OPTIONAL INTERNAL NAME</span>{editing ? <input autoFocus value={project.projectName} aria-label="Optional internal project name" onChange={(event) => update({ ...project, projectName: event.target.value, isProjectNameManuallyEdited: true })} onBlur={() => { if (!project.projectName.trim()) update(refreshProjectName({ ...project, isProjectNameManuallyEdited: false }, true)); setEditing(false); }} /> : <strong>{project.projectName}</strong>}<small>Private workspace label. Never copied to a marketplace automatically.</small></div><button aria-label="Edit project name" onMouseDown={(event) => event.preventDefault()} onClick={() => setEditing(true)}>✎</button></div>
      <div className="form-grid"><label className="field"><span>Primary target room · required</span><select value={project.primaryTargetRoom} onChange={(event) => setRoom("primaryTargetRoom", event.target.value)}><option value="">Select a room</option>{rooms.map((room) => <option key={room}>{room}</option>)}</select>{errors.primaryTargetRoom && <small className="error">{errors.primaryTargetRoom}</small>}</label><label className="field"><span>Secondary room · optional</span><select value={project.secondaryTargetRoom} onChange={(event) => setRoom("secondaryTargetRoom", event.target.value)}><option value="">Choose later</option>{rooms.filter((room) => room !== project.primaryTargetRoom).map((room) => <option key={room}>{room}</option>)}</select></label></div>
      <fieldset className="choice-set"><legend>Product type</legend><div className="product-grid">{(["seamless", "mural"] as ProductType[]).map((type) => <button key={type} className={project.productType === type ? "selected" : ""} onClick={() => update(changeProductType(project, type))}><i>{type === "seamless" ? "↻" : "▭"}</i><strong>{type === "seamless" ? "Seamless Pattern" : "Mural"}</strong><small>{type === "seamless" ? "Repeatable square artwork for continuous wallpaper printing." : "Custom-ratio panoramic artwork for a specific wall."}</small></button>)}</div></fieldset>
      {project.productType === "seamless" ? <fieldset className="choice-set"><legend>Pattern scale · required</legend><div className="scale-grid">{(["small", "medium", "large"] as PatternScale[]).map((scale) => <button key={scale} className={project.patternScale === scale ? "selected" : ""} onClick={() => update(setPatternScale(project, scale))}><strong>{scale}</strong><small>{scale === "small" ? "Small motifs with frequent repetition." : scale === "medium" ? "Balanced motif size and spacing." : "Large statement motifs with more impact."}</small></button>)}</div>{errors.patternScale && <small className="error">{errors.patternScale}</small>}</fieldset> : <div className="dimensions"><div className="section-label"><div><span>WALL DIMENSIONS</span><h2>Set the composition ratio.</h2></div><strong>{project.calculatedAspectRatio || "—"}</strong></div><div className="form-grid three"><label className="field"><span>Width</span><input type="number" min="0.01" placeholder="400" value={project.physicalWidth ?? ""} onChange={(event) => update(updateMeasurements(project, { width: event.target.value ? Number(event.target.value) : null }))} />{errors.physicalWidth && <small className="error">{errors.physicalWidth}</small>}</label><label className="field"><span>Height</span><input type="number" min="0.01" placeholder="250" value={project.physicalHeight ?? ""} onChange={(event) => update(updateMeasurements(project, { height: event.target.value ? Number(event.target.value) : null }))} />{errors.physicalHeight && <small className="error">{errors.physicalHeight}</small>}</label><label className="field"><span>Unit</span><select value={project.measurementUnit ?? ""} onChange={(event) => update(updateMeasurements(project, { unit: event.target.value ? event.target.value as "cm" | "inch" : null }))}><option value="">Select</option><option>cm</option><option>inch</option></select>{errors.measurementUnit && <small className="error">{errors.measurementUnit}</small>}</label></div><p>Wall dimensions determine the composition ratio. Final print resolution is checked in Design Master.</p></div>}
    </div>
    <div className="master-rule"><div><span>PRODUCTION MASTER</span><h2>{project.productType === "seamless" ? "Clean repeat artwork" : "Clean panoramic artwork"}</h2><div>{masterTags.map((tag) => <em key={tag}>{tag}</em>)}</div></div><b>≠</b><div><span>MARKETING MOCKUPS</span><h2>Presentation assets</h2><p>Derived later without redrawing or changing the source design.</p></div></div>
    <div className="actions"><small>Demo project auto-saves on this device.</small><button className="primary" disabled={!canContinue} title={!canContinue ? "Complete the required project details to continue." : undefined} onClick={next}>Build prompt →</button></div>
  </section>;
}

function PromptStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  const setPrompt = <K extends keyof PromptSpec>(key: K, value: PromptSpec[K]) => {
    const changed = { ...project, prompt: { ...project.prompt, [key]: value } };
    update(key === "theme" ? refreshProjectName(changed) : changed);
  };
  const generate = () => update({ ...project, status: "prompt_ready", prompt: { ...project.prompt, promptText: compilePrompt(project) } });
  return <section className="stage"><StepTitle number="02" eyebrow="PROMPT STUDIO" title="Direct the idea. Keep the source clean." copy="Structured choices compile into an editable production prompt." /><div className="studio-grid"><div className="paper-card form-card"><div className="form-grid"><Select label="Theme" value={project.prompt.theme} values={themes} onChange={(value) => setPrompt("theme", value)} /><Select label="Style" value={project.prompt.style} values={styles} onChange={(value) => setPrompt("style", value)} /><Select label="Palette" value={project.prompt.palette} values={palettes} onChange={(value) => setPrompt("palette", value)} /><Field label="Main motifs" value={project.prompt.motifs} onChange={(value) => setPrompt("motifs", value)} /><Field label="Exclude" value={project.prompt.exclusions} onChange={(value) => setPrompt("exclusions", value)} /><Select label="Density" value={project.prompt.density} values={["airy", "balanced", "dense"]} onChange={(value) => setPrompt("density", value as PromptSpec["density"])} /></div><button className="dark full" onClick={generate}>Generate production prompt ✦</button></div><div className="prompt-card"><div><span>PRODUCTION PROMPT</span><button disabled={!project.prompt.promptText} onClick={() => navigator.clipboard.writeText(project.prompt.promptText)}>Copy</button></div><textarea aria-label="Generated prompt" value={project.prompt.promptText || "Choose your direction, then generate a prompt."} onChange={(event) => setPrompt("promptText", event.target.value)} /><p>Production guardrail: no room, furniture, perspective, logo, text or watermark.</p></div></div><div className="actions"><small>{project.productType === "seamless" ? "Includes --tile --ar 1:1" : `Includes --ar ${project.calculatedAspectRatio}`}</small><button className="primary" disabled={!project.prompt.promptText} onClick={next}>Continue to Design Master →</button></div></section>;
}

async function imageAsset(file: File, project: Project) {
  const buffer = await file.arrayBuffer();
  const digest = await crypto.subtle.digest("SHA-256", buffer);
  const hash = [...new Uint8Array(digest)].map((item) => item.toString(16).padStart(2, "0")).join("");
  const originalUrl = URL.createObjectURL(file);
  const image = new Image();
  await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = reject; image.src = originalUrl; });
  const scale = Math.min(1, 1000 / Math.max(image.naturalWidth, image.naturalHeight));
  const canvas = document.createElement("canvas"); canvas.width = Math.round(image.naturalWidth * scale); canvas.height = Math.round(image.naturalHeight * scale);
  canvas.getContext("2d")?.drawImage(image, 0, 0, canvas.width, canvas.height); URL.revokeObjectURL(originalUrl);
  return { id: `asset-${crypto.randomUUID()}`, projectId: project.id, userId: project.userId, role: "production_master" as const, fileUrl: canvas.toDataURL("image/jpeg", .82), fileName: file.name, width: image.naturalWidth, height: image.naturalHeight, fileHash: hash, version: (project.productionMaster?.version ?? 0) + 1, createdAt: new Date().toISOString() };
}

function DesignStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  const input = useRef<HTMLInputElement>(null);
  const runQa = () => { const master = project.productionMaster; const enough = Boolean(master && master.width >= Math.max(project.requiredPixelWidth, 2000) && master.height >= Math.max(project.requiredPixelHeight, 2000)); update({ ...project, qa: { status: enough ? "pass" : "warn", score: enough ? 96 : 78, notes: master ? ["Production Master is isolated from staged scenes.", enough ? "Pixel dimensions meet the current profile." : "Upscaling may be required for final print size."] : ["Upload a Production Master first."] }, status: master ? "master_ready" : project.status }); };
  return <section className="stage"><StepTitle number="03" eyebrow="DESIGN MASTER" title="Upload once. Derive everything." copy="The source artwork stays separate from every marketing scene." /><div className="master-grid"><div className="paper-card upload-card"><input ref={input} hidden type="file" accept="image/*" onChange={async (event) => { const file = event.target.files?.[0]; if (file) update({ ...project, productionMaster: await imageAsset(file, project), qa: { status: "not_run", score: 0, notes: [] } }); }} /><button className="upload" style={project.productionMaster ? { backgroundImage: `url(${project.productionMaster.fileUrl})` } : undefined} onClick={() => input.current?.click()}><span>{project.productionMaster ? "Replace Production Master" : "+ Upload Production Master"}</span></button><dl><div><dt>ROLE</dt><dd>Production Master</dd></div><div><dt>VERSION</dt><dd>v{project.productionMaster?.version ?? 0}</dd></div><div><dt>PIXELS</dt><dd>{project.productionMaster ? `${project.productionMaster.width} × ${project.productionMaster.height}` : "Waiting"}</dd></div><div><dt>HASH</dt><dd>{project.productionMaster ? `${project.productionMaster.fileHash.slice(0, 9)}…` : "—"}</dd></div></dl></div><div className="paper-card form-card"><div className="section-label"><div><span>PRINT PROFILE</span><h2>{project.productType === "seamless" ? "Repeat QA" : "Panoramic QA"}</h2></div><strong>{project.targetPrintPpi} PPI</strong></div><div className="qa-list"><p>✓ Master and mockups use separate asset roles.</p><p>✓ Physical size and composition ratio remain separate.</p><p>✓ Final pixel sufficiency is checked here.</p></div><button className="dark full" disabled={!project.productionMaster} onClick={runQa}>Run production QA →</button>{project.qa.status !== "not_run" && <div className={`qa-result ${project.qa.status}`}><strong>{project.qa.score}/100</strong><div>{project.qa.notes.map((note) => <p key={note}>{note}</p>)}</div></div>}</div></div><div className="actions"><small>Uploads remain local in demo mode.</small><button className="primary" disabled={!project.productionMaster || project.qa.status === "not_run"} onClick={next}>Approve master →</button></div></section>;
}

function DirectionStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  return <section className="stage"><StepTitle number="04" eyebrow="ART DIRECTION" title="Classify before you stage." copy="Collection, mood and scale guide every marketing scene without changing the source." /><div className="recommendation"><div><span>PRIMARY RECOMMENDATION</span><h2>{project.collection}</h2><p>Based on {project.primaryTargetRoom}, {project.prompt.theme.toLowerCase()} motifs and the selected palette.</p></div><b>91% MATCH</b></div><div className="paper-card form-card"><div className="form-grid three"><Select label="Collection" value={project.collection} values={collections} onChange={(collection) => update({ ...project, collection })} /><Select label="Mood" value={project.mood} values={moods} onChange={(mood) => update({ ...project, mood })} /><Select label="Pattern scale" value={project.patternScale ?? "mural"} values={project.productType === "mural" ? ["mural"] : ["small", "medium", "large"]} onChange={(value) => update({ ...project, patternScale: value === "mural" ? null : value as PatternScale })} /></div></div><div className="scene-plan"><article><span>PRIMARY SETTING</span><strong>{project.primaryTargetRoom}</strong><small>Hero and lifestyle</small></article><article><span>SECONDARY SETTING</span><strong>{project.secondaryTargetRoom || "Auto-select"}</strong><small>One supporting scene</small></article><article><span>SOURCE POLICY</span><strong>Asset locked</strong><small>No regeneration</small></article></div><div className="actions"><small>All six roles inherit the approved master.</small><button className="primary" onClick={next}>Open Render Queue →</button></div></section>;
}

function RenderStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  const ready = project.slots.filter((slot) => slot.status === "ready").length;
  const render = (id?: string) => update({ ...project, status: "mockups_ready", slots: project.slots.map((slot) => !id || slot.id === id ? { ...slot, status: "ready", version: slot.version + 1 } : slot) });
  return <section className="stage"><StepTitle number="05" eyebrow="RENDER QUEUE" title="Six roles. One approved source." copy="Each slot can be regenerated independently without redrawing the wallpaper." /><div className="queue-head"><div><span>READY</span><strong>{ready}/6</strong></div><div><span>RENDERER</span><strong>Demo adapter</strong></div><div><span>SOURCE</span><strong>Master v{project.productionMaster?.version ?? 0}</strong></div><button className="dark" onClick={() => render()}>Render all six</button></div><div className="mockup-grid">{project.slots.map((slot, index) => <article key={slot.id}><div className={`scene scene-${index + 1}`} style={project.productionMaster ? { backgroundImage: `url(${project.productionMaster.fileUrl})` } : undefined}><i /><span>{slot.status === "ready" ? "READY" : "WAITING"}</span></div><footer><div><small>M{index + 1} · v{slot.version}</small><strong>{slot.role}</strong></div><button aria-label={`Regenerate ${slot.role}`} onClick={() => render(slot.id)}>↻</button></footer></article>)}</div><div className="actions"><small>Individual regeneration is idempotent by slot and version.</small><button className="primary" disabled={ready !== 6} onClick={next}>Open Listing Studio →</button></div></section>;
}

function ListingStep({ project, update }: { project: Project; update: (project: Project) => void }) {
  const [message, setMessage] = useState("");
  const listing = project.listing;
  const setListing = <K extends keyof typeof listing>(key: K, value: typeof listing[K]) => update({ ...project, listing: { ...listing, [key]: value } });
  const generateCopy = () => update({ ...project, status: "listing_ready", listing: { ...listing, title: `${project.prompt.theme} ${project.primaryTargetRoom} ${project.productType === "mural" ? "Wall Mural" : "Wallpaper Pattern"}`, description: `A ${project.mood.toLowerCase()} ${project.prompt.theme.toLowerCase()} wallpaper created for ${project.primaryTargetRoom.toLowerCase()} interiors. Prepared from a clean, approved Production Master.`, tags: [project.prompt.theme.toLowerCase(), project.primaryTargetRoom.toLowerCase(), project.productType, project.collection.toLowerCase(), project.mood.toLowerCase(), "wallpaper design", "interior decor"] } });
  const exportZip = async () => { const blob = await exporter.exportProject(project); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${project.projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.zip`; anchor.click(); URL.revokeObjectURL(url); setMessage("Project ZIP exported locally."); };
  const createDraft = async () => { const key = `${project.userId}:${project.id}:${listing.id}`; const result = await marketplace.createDraft({ userId: DEMO_USER_ID, project, listing, idempotencyKey: key }); update({ ...project, listing: { ...listing, status: "drafted", etsyListingId: result.externalId, idempotencyKey: key } }); setMessage(`Mock draft ${result.externalId} created. No API request was sent.`); };
  return <section className="stage"><StepTitle number="06" eyebrow="LISTING STUDIO" title="Export freely. Connect later." copy="Prepare marketplace content without an Etsy account, then choose ZIP export or an optional adapter." /><div className="listing-grid"><div className="paper-card form-card"><button className="generate-copy" onClick={generateCopy}>Generate listing copy ✦</button><label className="opt-in"><input type="checkbox" checked={listing.useProjectNameAsTitleSuggestion} onChange={(event) => update({ ...project, listing: { ...listing, useProjectNameAsTitleSuggestion: event.target.checked, title: event.target.checked ? project.projectName : listing.title } })} /><span><strong>Use project name as a listing title suggestion</strong><small>Off by default. Project names never flow into customer-facing fields automatically.</small></span></label><Field label={`Title · ${listing.title.length}/140`} value={listing.title} onChange={(value) => setListing("title", value.slice(0, 140))} /><label className="field"><span>Description</span><textarea value={listing.description} onChange={(event) => setListing("description", event.target.value)} /></label><label className="field"><span>Tags · comma separated</span><textarea value={listing.tags.join(", ")} onChange={(event) => setListing("tags", event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean).slice(0, 13))} /></label></div><aside className="listing-preview"><div className="preview-art" style={project.productionMaster ? { backgroundImage: `url(${project.productionMaster.fileUrl})` } : undefined}><span>HERO · SOURCE LOCKED</span></div><div><h2>{listing.title}</h2><strong>${listing.price}</strong><p>{listing.description}</p><div>{listing.tags.map((tag) => <em key={tag}>{tag}</em>)}</div></div></aside></div><div className="export-panel"><div><span>NO MARKETPLACE REQUIRED</span><h2>Export Project ZIP</h2><p>Production Master, prompts, six mockup manifests, listing content and project metadata.</p></div><button className="primary" onClick={exportZip}>Download ZIP ↓</button></div><div className="integration-panel"><div><span>OPTIONAL INTEGRATION</span><h2>Etsy adapter</h2><p>Demo mode uses an in-memory adapter and never contacts Etsy. Real OAuth credentials remain server-side.</p></div><button className="ghost" onClick={() => setMessage("Configure your own Etsy environment variables to enable OAuth.")}>Connect Etsy</button><button className="dark" onClick={createDraft}>{listing.etsyListingId ? "Return demo draft" : "Create demo draft"}</button></div>{message && <div className="notice" role="status">✓ {message}</div>}</section>;
}

export default function StudioApp() {
  const [project, setProject] = useState<Project | null>(null);
  const [step, setStep] = useState(0);
  useEffect(() => {
    const timer = window.setTimeout(() => {
      try { const saved = localStorage.getItem(STORAGE_KEY); setProject(saved ? JSON.parse(saved) as Project : createDemoProject()); }
      catch { setProject(createDemoProject()); }
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => { if (project) localStorage.setItem(STORAGE_KEY, JSON.stringify(project)); }, [project]);
  const progress = useMemo(() => Math.round(((step + 1) / steps.length) * 100), [step]);
  if (!project) return <div className="loading"><span>W</span><p>Preparing the studio…</p></div>;
  const update = (next: Project) => setProject({ ...next, updatedAt: new Date().toISOString() });
  const newProject = () => { if (!confirm("Start a new demo project?")) return; setProject(createDemoProject(DEMO_USER_ID, project.projectSequenceNumber + 1)); setStep(0); };
  return <div className="studio-app"><header className="topbar"><button className="brand" onClick={() => setStep(0)}><span>W</span><strong>Wallpaper AI Studio<small>OPEN-SOURCE WORKFLOW</small></strong></button><div className="active-project"><span>ACTIVE PROJECT</span><strong>{project.projectName}</strong><small>DEMO MODE</small></div><nav><a href="https://github.com/berrakorkmaz/wallpaper-ai-studio" target="_blank" rel="noreferrer">GitHub ↗</a><button onClick={newProject}>＋ New project</button></nav></header><div className="app-shell"><aside className="workflow"><div className="workflow-progress"><span>Step {step + 1} of 6</span><b>{progress}% complete</b></div><ol>{steps.map(([number, title, copy], index) => <li key={number} className={index === step ? "active" : index < step ? "done" : ""}><button onClick={() => setStep(index)}><span>{index < step ? "✓" : number}</span><div><strong>{title}</strong><small>{copy}</small></div></button></li>)}</ol><div className="system"><span>SYSTEM</span><p>● Demo storage</p><p>● Mock adapters</p><p>● Publish disabled</p></div></aside><main>{step === 0 && <ProductStep project={project} update={update} next={() => setStep(1)} />}{step === 1 && <PromptStep project={project} update={update} next={() => setStep(2)} />}{step === 2 && <DesignStep project={project} update={update} next={() => setStep(3)} />}{step === 3 && <DirectionStep project={project} update={update} next={() => setStep(4)} />}{step === 4 && <RenderStep project={project} update={update} next={() => setStep(5)} />}{step === 5 && <ListingStep project={project} update={update} />}</main><aside className="policy"><span>OPEN CORE</span><h2>Marketplace optional.</h2><p>The studio works from project brief to local ZIP without OAuth.</p><ul><li>Production Master isolated</li><li>User-owned records</li><li>Adapter-based services</li><li>Draft-only marketplace</li></ul><b>MIT LICENSED</b></aside></div></div>;
}
