"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ZipExportAdapter, type ExportPackageType } from "../integrations/export/index.ts";
import { approveOutput, completeRenderJob, requestRenderJobs } from "../lib/core/render.ts";
import { allOutputsReady, canRender, changeProductType, createDemoProject, markSlotsStaleForNewMaster, refreshProjectName, setPatternScale, updateMeasurements, validateProject, workflowStates } from "../lib/core/project.ts";
import { compilePrompt } from "../lib/core/prompt.ts";
import { evaluateMasterQa } from "../lib/core/qa.ts";
import type { DesignAsset, OutputAsset, PatternScale, ProductType, Project, PromptSpec, RenderJob, RenderProvider } from "../lib/core/types.ts";

const STORAGE_KEY = "wallpaper-ai-studio-demo-v2";
const DEMO_USER_ID = "demo-user";
const RENDER_PROVIDER: RenderProvider = "mock";
const exporter = new ZipExportAdapter();
const steps = [["01", "Project", "Product & room"], ["02", "Prompt Studio", "Creative direction"], ["03", "Design Master", "Upload & print QA"], ["04", "Art Direction", "Collection & mood"], ["05", "Render Queue", "10 independent outputs"], ["06", "Listing Studio", "Export or draft"]] as const;
const rooms = ["Nursery", "Kids Room", "Living Room", "Bedroom", "Gaming Room", "Office / Studio", "Bathroom / Powder", "Dining / Entryway"];
const themes = ["Woodland", "Botanical", "Dark Floral", "Pink Bows", "Celestial", "Coastal", "Geometric", "Neon Gaming"];
const styles = ["Hand-painted gouache", "Watercolor", "Engraved", "Vintage textile", "Minimal line art", "Painterly editorial"];
const palettes = ["Warm woodland", "Dusty rose & sage", "Midnight jewel", "Coastal mineral", "Soft neutral", "Sun-washed terracotta"];
const collections = ["Baby & Nursery", "Kids Room", "Gaming Room", "Dark & Moody", "Living Room", "Bedroom", "Office / Studio", "Bathroom / Powder", "Dining / Entryway", "General Editorial"];
const moods = ["Soft & airy", "Warm neutral", "Playful", "Cinematic", "Organic elegant", "Romantic", "Clean refined"];

function Field({ label, value, onChange, type = "text", placeholder }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label>; }
function Select({ label, value, values, onChange }: { label: string; value: string; values: readonly string[]; onChange: (value: string) => void }) { return <label className="field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function StepTitle({ number, eyebrow, title, copy }: { number: string; eyebrow: string; title: string; copy: string }) { return <header className="step-title"><b>{number}</b><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></header>; }
function downloadBlob(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 500); }

function ProductStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  const [editing, setEditing] = useState(false); const errors = validateProject(project); const canContinue = Object.keys(errors).length === 0;
  const setRoom = (key: "primaryTargetRoom" | "secondaryTargetRoom", value: string) => { const changed = { ...project, [key]: value, artDirection: { ...project.artDirection, [key]: value } }; update(key === "primaryTargetRoom" ? refreshProjectName(changed) : changed); };
  return <section className="stage"><StepTitle number="01" eyebrow="NEW PROJECT" title="Start with one source of truth." copy="Project naming stays internal. Product dimensions drive every later quality check." />
    <div className="paper-card form-card"><div className="project-name"><div><span>OPTIONAL INTERNAL NAME</span>{editing ? <input autoFocus value={project.projectName} aria-label="Optional internal project name" onChange={(event) => update({ ...project, projectName: event.target.value, isProjectNameManuallyEdited: true })} onBlur={() => setEditing(false)} /> : <><h2>{project.projectName}</h2><small>Generated automatically · never copied to Etsy</small></>}</div><button aria-label="Edit project name" onClick={() => setEditing(true)}>✎</button></div>
      <fieldset className="choice-set"><legend>Product type</legend><div className="product-grid">{(["seamless", "mural"] as ProductType[]).map((type) => <button key={type} className={project.productType === type ? "selected" : ""} onClick={() => update(changeProductType(project, type))}><strong>{type === "seamless" ? "Seamless Pattern" : "Custom Mural"}</strong><small>{type === "seamless" ? "Repeat-ready square artwork" : "Wall-specific panoramic artwork"}</small></button>)}</div></fieldset>
      <div className="form-grid"><Select label="Primary target room" value={project.primaryTargetRoom} values={rooms} onChange={(value) => setRoom("primaryTargetRoom", value)} /><Select label="Secondary room" value={project.secondaryTargetRoom} values={["", ...rooms]} onChange={(value) => setRoom("secondaryTargetRoom", value)} /></div>
      {project.productType === "seamless" ? <fieldset className="choice-set"><legend>Pattern scale</legend><div className="scale-grid">{(["small", "medium", "large"] as PatternScale[]).map((scale) => <button key={scale} className={project.patternScale === scale ? "selected" : ""} onClick={() => update(setPatternScale(project, scale))}><strong>{scale}</strong><small>{scale === "small" ? "Frequent repeat" : scale === "medium" ? "Balanced repeat" : "Statement scale"}</small></button>)}</div>{errors.patternScale && <small className="error">{errors.patternScale}</small>}</fieldset> : <div className="dimensions"><div className="section-label"><div><span>WALL DIMENSIONS</span><h2>Set the composition ratio.</h2></div><strong>{project.calculatedAspectRatio || "—"}</strong></div><div className="form-grid three"><label className="field"><span>Width</span><input type="number" min="0.01" value={project.physicalWidth ?? ""} onChange={(event) => update(updateMeasurements(project, { width: event.target.value ? Number(event.target.value) : null }))} />{errors.physicalWidth && <small className="error">{errors.physicalWidth}</small>}</label><label className="field"><span>Height</span><input type="number" min="0.01" value={project.physicalHeight ?? ""} onChange={(event) => update(updateMeasurements(project, { height: event.target.value ? Number(event.target.value) : null }))} />{errors.physicalHeight && <small className="error">{errors.physicalHeight}</small>}</label><label className="field"><span>Unit</span><select value={project.measurementUnit ?? ""} onChange={(event) => update(updateMeasurements(project, { unit: event.target.value ? event.target.value as "cm" | "inch" : null }))}><option value="">Select</option><option>cm</option><option>inch</option></select>{errors.measurementUnit && <small className="error">{errors.measurementUnit}</small>}</label></div></div>}
    </div><div className="master-rule"><div><span>PRODUCTION MASTER</span><h2>Clean, immutable artwork</h2><p>No room, furniture, perspective, copy or watermark.</p></div><b>≠</b><div><span>MARKETING OUTPUTS</span><h2>Derived presentation assets</h2><p>Mask and perspective compositing never redraw the source.</p></div></div><div className="actions"><small>Saved locally in this public demo.</small><button className="primary" disabled={!canContinue} onClick={next}>Build prompt →</button></div></section>;
}

function PromptStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  const setPrompt = <K extends keyof PromptSpec>(key: K, value: PromptSpec[K]) => { const changed = { ...project, prompt: { ...project.prompt, [key]: value, selectedAt: key === "promptText" ? new Date().toISOString() : project.prompt.selectedAt } }; update(key === "theme" ? refreshProjectName(changed) : changed); };
  const generate = () => update({ ...project, prompt: { ...project.prompt, promptText: compilePrompt(project), selectedAt: new Date().toISOString() } });
  return <section className="stage"><StepTitle number="02" eyebrow="PROMPT STUDIO" title="Direct the artwork—not the room." copy="Generate the prompt here, create the design in Midjourney, then upload only your chosen artwork." /><div className="studio-grid"><div className="paper-card form-card"><div className="form-grid"><Select label="Theme" value={project.prompt.theme} values={themes} onChange={(value) => setPrompt("theme", value)} /><Select label="Style" value={project.prompt.style} values={styles} onChange={(value) => setPrompt("style", value)} /><Select label="Palette" value={project.prompt.palette} values={palettes} onChange={(value) => setPrompt("palette", value)} /><Field label="Main motifs" value={project.prompt.motifs} onChange={(value) => setPrompt("motifs", value)} /><Field label="Exclude" value={project.prompt.exclusions} onChange={(value) => setPrompt("exclusions", value)} /><Select label="Density" value={project.prompt.density} values={["airy", "balanced", "dense"]} onChange={(value) => setPrompt("density", value as PromptSpec["density"])} /></div><button className="dark full" onClick={generate}>Generate production prompt ✦</button></div><div className="prompt-card"><div><span>SELECTED PRODUCTION PROMPT</span><button disabled={!project.prompt.promptText} onClick={() => navigator.clipboard.writeText(project.prompt.promptText)}>Copy</button></div><textarea aria-label="Generated prompt" value={project.prompt.promptText || "Choose your direction, then generate a prompt."} onChange={(event) => setPrompt("promptText", event.target.value)} /><p>No room · no furniture · no perspective · no logo · no text · no watermark</p></div></div><div className="actions"><small>{project.productType === "seamless" ? "Includes --tile --ar 1:1" : `Includes --ar ${project.calculatedAspectRatio}`}</small><button className="primary" disabled={!project.prompt.promptText || !project.prompt.selectedAt} onClick={next}>I created my design →</button></div></section>;
}

async function inspectImage(file: File, project: Project) {
  const buffer = await file.arrayBuffer(); const digest = await crypto.subtle.digest("SHA-256", buffer); const hash = [...new Uint8Array(digest)].map((item) => item.toString(16).padStart(2, "0")).join("");
  const fileUrl = URL.createObjectURL(file); const image = new Image(); await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = reject; image.src = fileUrl; });
  const probe = document.createElement("canvas"); probe.width = Math.min(image.naturalWidth, 128); probe.height = Math.min(image.naturalHeight, 128); const context = probe.getContext("2d", { willReadFrequently: true })!; context.drawImage(image, 0, 0, probe.width, probe.height); const pixels = context.getImageData(0, 0, probe.width, probe.height).data;
  let alpha = false; for (let i = 3; i < pixels.length; i += 4) if (pixels[i] < 255) { alpha = true; break; }
  const edgeDiff = (horizontal: boolean) => { let total = 0; const count = horizontal ? probe.height : probe.width; for (let i = 0; i < count; i++) { const a = horizontal ? (i * probe.width) * 4 : i * 4; const b = horizontal ? (i * probe.width + probe.width - 1) * 4 : ((probe.height - 1) * probe.width + i) * 4; total += (Math.abs(pixels[a] - pixels[b]) + Math.abs(pixels[a + 1] - pixels[b + 1]) + Math.abs(pixels[a + 2] - pixels[b + 2])) / 3; } return total / count; };
  const asset: DesignAsset = { id: `master-${crypto.randomUUID()}`, projectId: project.id, userId: project.userId, role: "production_master", fileUrl, fileName: file.name, width: image.naturalWidth, height: image.naturalHeight, fileHash: hash, version: project.masterVersions.length + 1, createdAt: new Date().toISOString(), mimeType: file.type, fileSize: file.size, aspectRatio: image.naturalWidth / image.naturalHeight, colorProfile: "sRGB", hasTransparency: alpha, immutable: true, approvedAt: null };
  return { asset, edges: { horizontal: edgeDiff(true), vertical: edgeDiff(false), motifCutRisk: edgeDiff(true) > 12 || edgeDiff(false) > 12 } };
}

function DesignStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  const input = useRef<HTMLInputElement>(null); const [edges, setEdges] = useState<{ horizontal: number; vertical: number; motifCutRisk: boolean }>();
  const upload = async (file: File) => { const inspected = await inspectImage(file, project); setEdges(inspected.edges); update({ ...project, productionMaster: inspected.asset, masterVersions: [...project.masterVersions, inspected.asset], activeMasterVersionId: inspected.asset.id, masterStatus: "UPLOADED", qa: { ...project.qa, status: "UPLOADED", checks: [] }, slots: markSlotsStaleForNewMaster(project) }); };
  const runQa = () => { if (!project.productionMaster) return; const qa = evaluateMasterQa(project, project.productionMaster, edges); update({ ...project, masterStatus: qa.status, qa }); };
  const approve = () => { if (!project.productionMaster || project.masterStatus !== "QA_PASSED") return; const master = { ...project.productionMaster, approvedAt: new Date().toISOString() }; update({ ...project, productionMaster: master, masterVersions: project.masterVersions.map((item) => item.id === master.id ? master : item), masterStatus: "APPROVED" }); next(); };
  const master = project.productionMaster;
  return <section className="stage"><StepTitle number="03" eyebrow="DESIGN MASTER" title="Upload once. Preserve forever." copy="Every upload creates a new immutable master version. Existing renders remain linked to the version that created them." /><div className="master-grid"><div className="paper-card upload-card"><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) upload(file); }} /><button className="upload" style={master ? { backgroundImage: `url(${master.fileUrl})` } : undefined} onClick={() => input.current?.click()}><span>{master ? "Upload new master version" : "+ Upload Design Master"}</span></button><dl><div><dt>STATUS</dt><dd>{project.masterStatus}</dd></div><div><dt>VERSION</dt><dd>v{master?.version ?? 0}</dd></div><div><dt>PIXELS</dt><dd>{master ? `${master.width} × ${master.height}` : "Waiting"}</dd></div><div><dt>FILE</dt><dd>{master ? `${(master.fileSize / 1024 / 1024).toFixed(1)} MB` : "—"}</dd></div><div><dt>PROFILE</dt><dd>{master?.colorProfile ?? "—"}</dd></div><div><dt>HASH</dt><dd>{master ? `${master.fileHash.slice(0, 10)}…` : "—"}</dd></div></dl></div>
    <div className="paper-card form-card"><div className="section-label"><div><span>{project.productType === "seamless" ? "SEAMLESS QA" : "MURAL QA"}</span><h2>{project.productType === "seamless" ? "Repeat integrity" : "Crop & safe area"}</h2></div><strong>{project.targetPrintPpi} PPI</strong></div>{master && <div className={project.productType === "seamless" ? "repeat-preview" : "crop-preview"} style={{ backgroundImage: `url(${master.fileUrl})` }}><span>{project.productType === "seamless" ? "3 × 3 REPEAT" : "CROP / PANEL SAFE AREA"}</span></div>}<button className="dark full" disabled={!master} onClick={runQa}>Run production QA →</button>{project.qa.checks.length > 0 && <><div className={`qa-summary ${project.masterStatus === "QA_FAILED" ? "failed" : "passed"}`}><strong>{project.qa.score}/100</strong><div><b>{project.masterStatus}</b><small>Current {master?.width} × {master?.height}px · Required {project.qa.requiredWidth} × {project.qa.requiredHeight}px</small>{project.qa.upscaleRequired && <em>Upscale required: +{project.qa.missingWidth}px wide, +{project.qa.missingHeight}px high. DPI metadata alone will not pass.</em>}</div></div><div className="qa-checks">{project.qa.checks.map((item) => <div key={item.key} data-state={item.status}><b>{item.status === "pass" ? "✓" : item.status === "warn" ? "!" : "×"}</b><span><strong>{item.label}</strong><small>{item.detail}</small></span></div>)}</div></>}</div></div><div className="actions"><small>Mockups cannot start until QA passes.</small><button className="primary" disabled={project.masterStatus !== "QA_PASSED"} onClick={approve}>Approve Production Master →</button></div></section>;
}

function DirectionStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  const setDirection = (patch: Partial<Project["artDirection"]>) => update({ ...project, artDirection: { ...project.artDirection, ...patch, userOverridden: true }, collection: typeof patch.collection === "string" ? patch.collection : project.collection, mood: typeof patch.mood === "string" ? patch.mood : project.mood, patternScale: patch.patternScale === undefined ? project.patternScale : patch.patternScale });
  const save = () => { update({ ...project, artDirection: { ...project.artDirection, savedAt: new Date().toISOString() } }); next(); };
  return <section className="stage"><StepTitle number="04" eyebrow="ART DIRECTION" title="Choose the scene system." copy="These choices select scene templates; they never alter the approved wallpaper artwork." /><div className="recommendation"><div><span>AI RECOMMENDATION</span><h2>{project.artDirection.recommendation.collection}</h2><p>{project.artDirection.recommendation.reason}. You can override every field.</p></div><b>{project.artDirection.userOverridden ? "USER EDITED" : "91% MATCH"}</b></div><div className="paper-card form-card"><div className="form-grid three"><Select label="Collection" value={project.artDirection.collection} values={collections} onChange={(collection) => setDirection({ collection })} /><Select label="Mood" value={project.artDirection.mood} values={moods} onChange={(mood) => setDirection({ mood })} /><Select label="Pattern scale" value={project.artDirection.patternScale ?? "mural"} values={project.productType === "mural" ? ["mural"] : ["small", "medium", "large"]} onChange={(value) => setDirection({ patternScale: value === "mural" ? null : value as PatternScale })} /></div></div><div className="scene-plan"><article><span>PRIMARY SETTING</span><strong>{project.artDirection.primaryTargetRoom}</strong><small>Hero and lifestyle scenes</small></article><article><span>SECONDARY SETTING</span><strong>{project.artDirection.secondaryTargetRoom || "Auto-selected"}</strong><small>Secondary Setting only</small></article><article><span>SOURCE POLICY</span><strong>Composite only</strong><small>Mask · perspective · displacement · lighting</small></article></div><div className="actions"><small>Template set: {project.artDirection.collection} / {project.artDirection.mood}</small><button className="primary" disabled={!canRender(project)} onClick={save}>Save & open Render Queue →</button></div></section>;
}

function roundedRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) { ctx.beginPath(); ctx.roundRect(x, y, w, h, r); ctx.fill(); }
async function loadImage(url: string) { const image = new Image(); image.crossOrigin = "anonymous"; await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = reject; image.src = url; }); return image; }
async function compositeOutput(project: Project, job: RenderJob): Promise<{ asset: OutputAsset; blob: Blob }> {
  const master = project.productionMaster!; const source = await loadImage(master.fileUrl); const width = 3000; const height = job.slotRole === "Clean Design" || job.slotRole === "Repeat Map" || job.slotRole === "Mural Map" ? 3000 : 2250; const canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height; const ctx = canvas.getContext("2d")!;
  ctx.fillStyle = "#eee8dc"; ctx.fillRect(0, 0, width, height); const drawCover = (x: number, y: number, w: number, h: number, repeat = false) => { ctx.save(); ctx.beginPath(); ctx.rect(x, y, w, h); ctx.clip(); if (repeat) { const tile = Math.min(w / 3, h / 3); for (let row = 0; row < Math.ceil(h / tile); row++) for (let col = 0; col < Math.ceil(w / tile); col++) ctx.drawImage(source, x + col * tile, y + row * tile, tile, tile); } else { const scale = Math.max(w / source.width, h / source.height); const dw = source.width * scale; const dh = source.height * scale; ctx.drawImage(source, x + (w - dw) / 2, y + (h - dh) / 2, dw, dh); } ctx.restore(); };
  if (job.slotRole === "Clean Design") drawCover(120, 120, width - 240, height - 240, project.productType === "seamless");
  else if (job.slotRole === "Repeat Map" || job.slotRole === "Mural Map") { drawCover(180, 260, width - 360, height - 520, job.slotRole === "Repeat Map"); ctx.strokeStyle = "rgba(122,54,63,.75)"; ctx.lineWidth = 8; for (let i = 1; i < 3; i++) { ctx.beginPath(); ctx.moveTo(180 + (width - 360) * i / 3, 260); ctx.lineTo(180 + (width - 360) * i / 3, height - 260); ctx.stroke(); } }
  else if (job.slotRole === "Size Information" || job.slotRole === "Order Guide") { ctx.fillStyle = "#2a3632"; ctx.font = "120px Georgia"; ctx.fillText(job.slotRole, 180, 320); ctx.font = "58px Arial"; ctx.fillStyle = "#6d655d"; const lines = job.slotRole === "Order Guide" ? ["01  MEASURE", "02  CHOOSE", "03  ORDER"] : [`TYPE  ${project.productType.toUpperCase()}`, `RATIO  ${project.calculatedAspectRatio}`, `PROFILE  ${project.targetPrintPpi} PPI`, `SOURCE  ${master.width} × ${master.height} PX`]; lines.forEach((line, i) => ctx.fillText(line, 220, 650 + i * 230)); }
  else { const angle = ["Alternate Angle", "Secondary Setting"].includes(job.slotRole) ? 160 : 0; drawCover(angle, 0, width - angle, height * .78, project.productType === "seamless"); const shade = ctx.createLinearGradient(0, 0, width, height); shade.addColorStop(0, "rgba(255,255,255,.18)"); shade.addColorStop(1, "rgba(22,28,27,.22)"); ctx.fillStyle = shade; ctx.fillRect(0, 0, width, height * .78); ctx.fillStyle = "#d8cbbb"; ctx.fillRect(0, height * .78, width, height * .22); ctx.fillStyle = job.slotRole === "Secondary Setting" ? "#8d726a" : "#788479"; roundedRect(ctx, job.slotRole === "Wide Shot" ? 2100 : 500, 1450, job.slotRole === "Close-up" ? 450 : 1100, 500, 80); }
  ctx.fillStyle = "rgba(28,32,31,.85)"; ctx.font = "42px Arial"; ctx.fillText(`${job.slotRole.toUpperCase()} · DEVELOPMENT MOCK`, 90, height - 75);
  const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((value) => value ? resolve(value) : reject(new Error("ENCODE_FAILED")), "image/jpeg", .93)); const url = URL.createObjectURL(blob); const asset: OutputAsset = { id: `output-${crypto.randomUUID()}`, projectId: project.id, userId: project.userId, masterVersionId: master.id, slotId: job.slotId, role: job.slotRole, fileUrl: url, fileName: `${job.slotId}.jpg`, width, height, format: "jpg", fileSize: blob.size, productionReady: false, renderProvider: "mock", sceneTemplateId: job.sceneTemplateId, approved: false, rejected: false, createdAt: new Date().toISOString() }; return { asset, blob };
}

function RenderStep({ project, update, next }: { project: Project; update: (project: Project) => void; next: () => void }) {
  const [working, setWorking] = useState(false); const ready = project.slots.filter((slot) => slot.status === "ready").length; const approved = project.outputAssets.filter((asset) => asset.approved && project.slots.some((slot) => slot.outputAssetId === asset.id)).length;
  const render = async (ids: string[]) => { if (!canRender(project) || !project.artDirection.savedAt) return; setWorking(true); try { const requested = requestRenderJobs(project, project.userId, ids, RENDER_PROVIDER); let nextProject = requested.project; update(nextProject); for (const job of requested.jobs) { const rendered = await compositeOutput(nextProject, job); nextProject = completeRenderJob(nextProject, job.jobId, rendered.asset); update(nextProject); } } finally { setWorking(false); } };
  const download = async (asset: OutputAsset) => { const response = await fetch(asset.fileUrl); downloadBlob(await response.blob(), asset.fileName); };
  const decide = (assetId: string, value: boolean) => update(approveOutput(project, assetId, value));
  return <section className="stage"><StepTitle number="05" eyebrow="RENDER QUEUE" title="Ten jobs. One locked source." copy="Six scene mockups and four listing guides render independently. Regenerating one slot never changes the other nine." />{RENDER_PROVIDER === "mock" && <div className="provider-warning"><strong>Development mock renderer</strong><span>High-resolution previews are downloadable, but are not marked production-ready. Configure the real compositing service before commercial use.</span></div>}<div className="queue-head"><div><span>READY</span><strong>{ready}/10</strong></div><div><span>APPROVED</span><strong>{approved}/10</strong></div><div><span>SOURCE</span><strong>Master v{project.productionMaster?.version ?? 0}</strong></div><button className="dark" disabled={!canRender(project) || !project.artDirection.savedAt || working} onClick={() => render(project.slots.map((slot) => slot.id))}>{working ? "Rendering…" : "Render all 10 slots"}</button></div>{!canRender(project) && <div className="gate-notice">Upload a Design Master and pass QA before rendering.</div>}
    <div className="output-grid">{project.slots.map((slot, index) => { const asset = project.outputAssets.find((item) => item.id === slot.outputAssetId); const job = project.renderJobs.find((item) => item.jobId === slot.activeJobId); return <article key={slot.id} className={slot.status === "stale" ? "stale" : ""}><div className="output-preview" style={asset ? { backgroundImage: `url(${asset.fileUrl})` } : undefined}><span>{slot.kind === "mockup" ? `M${index + 1}` : `I${index - 5}`}</span><b>{slot.status.toUpperCase()}</b></div><div className="output-meta"><small>{slot.kind.toUpperCase()} · v{slot.version}</small><h3>{slot.role}</h3><p>{asset ? `${asset.width} × ${asset.height}px · ${asset.format.toUpperCase()} · ${(asset.fileSize / 1024 / 1024).toFixed(1)} MB` : "Waiting for render"}</p><p>Master v{project.masterVersions.find((item) => item.id === (asset?.masterVersionId || job?.masterVersionId))?.version ?? "—"} · {job?.sceneTemplateId || "scene pending"}</p>{asset && <em>{asset.productionReady ? "PRODUCTION READY" : "DEVELOPMENT OUTPUT"}</em>}</div><div className="output-actions"><button disabled={!asset} onClick={() => asset && download(asset)}>Download</button><button disabled={!canRender(project) || working} onClick={() => render([slot.id])}>Regenerate</button>{asset && <button className={asset.approved ? "approved" : ""} onClick={() => decide(asset.id, !asset.approved)}>{asset.approved ? "Approved ✓" : "Approve"}</button>}{asset && <button onClick={() => decide(asset.id, false)}>Reject</button>}</div></article>; })}</div><div className="actions"><small>Every output records provider, scene template, master version and idempotency key.</small><button className="primary" disabled={!allOutputsReady(project) || approved !== 10} onClick={next}>Open Listing Studio →</button></div></section>;
}

function ListingStep({ project, update }: { project: Project; update: (project: Project) => void }) {
  const [message, setMessage] = useState(""); const [exporting, setExporting] = useState(false); const listing = project.listing; const approvedCount = project.outputAssets.filter((asset) => asset.approved).length;
  const setListing = <K extends keyof typeof listing>(key: K, value: typeof listing[K]) => update({ ...project, listing: { ...listing, [key]: value } });
  const generateCopy = () => { const tags = [project.prompt.theme.toLowerCase(), project.primaryTargetRoom.toLowerCase(), project.productType, project.collection.toLowerCase(), project.mood.toLowerCase(), "wallpaper design", "interior decor", "wall covering", "designer wallpaper", "home styling", "statement wall", "premium decor", project.productType === "mural" ? "custom mural" : "repeat pattern"]; update({ ...project, listing: { ...listing, title: `${project.prompt.theme} ${project.primaryTargetRoom} ${project.productType === "mural" ? "Wall Mural" : "Wallpaper Pattern"}`, description: `A ${project.mood.toLowerCase()} ${project.prompt.theme.toLowerCase()} wallpaper created for ${project.primaryTargetRoom.toLowerCase()} interiors. Prepared from an approved Production Master.`, tags: tags.slice(0, 13), status: "ready" } }); };
  const exportZip = async (packageType: ExportPackageType) => { setExporting(true); try { const result = await exporter.exportProject({ project, userId: project.userId, packageType }); downloadBlob(result.blob, `${project.projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${packageType}.zip`); update({ ...project, exportJobs: [...project.exportJobs, result.job], listing: { ...project.listing, status: "exported" } }); setMessage(`${packageType} package downloaded. No Etsy connection was required.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Export failed."); } finally { setExporting(false); } };
  return <section className="stage"><StepTitle number="06" eyebrow="LISTING STUDIO" title="Package first. Connect only when ready." copy="Download your listing package without Etsy. Draft creation stays unavailable until a real shop connection exists." /><div className="listing-grid"><div className="paper-card form-card"><button className="generate-copy" onClick={generateCopy}>Generate listing copy ✦</button><label className="opt-in"><input type="checkbox" checked={listing.useProjectNameAsTitleSuggestion} onChange={(event) => update({ ...project, listing: { ...listing, useProjectNameAsTitleSuggestion: event.target.checked, title: event.target.checked ? project.projectName : listing.title } })} /><span><strong>Use project name as a listing title suggestion</strong><small>Off by default. Project names never flow into customer-facing fields automatically.</small></span></label><Field label={`Title · ${listing.title.length}/140`} value={listing.title} onChange={(value) => setListing("title", value.slice(0, 140))} /><label className="field"><span>Description</span><textarea value={listing.description} onChange={(event) => setListing("description", event.target.value)} /></label><label className="field"><span>13 tags · comma separated</span><textarea value={listing.tags.join(", ")} onChange={(event) => setListing("tags", event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean).slice(0, 13))} /></label><div className="form-grid three"><Field label="Price" value={listing.price} onChange={(value) => setListing("price", value)} /><Field label="Quantity" type="number" value={listing.quantity} onChange={(value) => setListing("quantity", Number(value))} /><Field label="Shipping profile" value={listing.shippingProfileId} onChange={(value) => setListing("shippingProfileId", value)} /></div><Field label="Production partner" value={listing.productionPartner} onChange={(value) => setListing("productionPartner", value)} /><Field label="Variations" value={listing.variations} onChange={(value) => setListing("variations", value)} /></div><aside className="listing-preview"><div className="preview-art" style={project.outputAssets.find((asset) => asset.role === "Hero" && asset.approved) ? { backgroundImage: `url(${project.outputAssets.find((asset) => asset.role === "Hero" && asset.approved)!.fileUrl})` } : undefined}><span>01 · HERO</span></div><div><h2>{listing.title}</h2><strong>${listing.price}</strong><p>{listing.description}</p><div>{listing.tags.map((tag) => <em key={tag}>{tag}</em>)}</div></div></aside></div>
    {approvedCount > 0 && <div className="export-panel"><div><span>SECURE LOCAL EXPORT</span><h2>Export Project</h2><p>Choose a focused package, or download the complete structured archive when all ten outputs are approved.</p></div><div className="export-buttons"><button disabled={exporting} onClick={() => exportZip("production")}>Production Files</button><button disabled={exporting} onClick={() => exportZip("mockups")}>Mockups Only</button><button disabled={exporting || approvedCount < 10} onClick={() => exportZip("listing-images")}>Listing Images</button><button disabled={exporting} onClick={() => exportZip("prompts")}>Prompt Package</button><button disabled={exporting} onClick={() => exportZip("listing-content")}>Listing Content</button><button className="primary" disabled={exporting || approvedCount < 10} onClick={() => exportZip("complete")}>Download Complete ZIP ↓</button></div></div>}
    <div className="integration-panel"><div><span>OPTIONAL INTEGRATION</span><h2>Etsy draft adapter</h2><p>Not connected. Download remains available; Etsy draft creation requires server-side OAuth and never publishes automatically.</p></div><button className="ghost" onClick={() => setMessage("Configure your own Etsy OAuth credentials and callback URL on the server.")}>Connection guide</button><button className="dark" disabled>Create Etsy Draft</button></div>{message && <div className="notice" role="status">{message}</div>}</section>;
}

function normalizeProject(raw: Project): Project { if (!raw.masterVersions || !raw.renderJobs || !raw.outputAssets || !raw.artDirection || raw.slots?.length !== 10) return createDemoProject(raw.userId || DEMO_USER_ID, raw.projectSequenceNumber || 1); return raw; }

export default function StudioApp() {
  const [project, setProject] = useState<Project | null>(null); const [step, setStep] = useState(0);
  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = localStorage.getItem(STORAGE_KEY); setProject(saved ? normalizeProject(JSON.parse(saved) as Project) : createDemoProject()); } catch { setProject(createDemoProject()); } }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (project) { const safe = { ...project, productionMaster: project.productionMaster?.fileUrl.startsWith("blob:") ? null : project.productionMaster, masterVersions: project.masterVersions.filter((asset) => !asset.fileUrl.startsWith("blob:")), outputAssets: [] }; try { localStorage.setItem(STORAGE_KEY, JSON.stringify(safe)); } catch { /* browser quota is non-critical in demo mode */ } } }, [project]);
  const states = useMemo(() => project ? workflowStates(project) : [], [project]); const progress = states.length ? Math.round(states.filter((item) => item.complete).length / states.length * 100) : 0;
  if (!project) return <div className="loading"><span>W</span><p>Preparing the studio…</p></div>;
  const update = (next: Project) => setProject({ ...next, updatedAt: new Date().toISOString() }); const newProject = () => { if (!confirm("Start a new demo project?")) return; setProject(createDemoProject(DEMO_USER_ID, project.projectSequenceNumber + 1)); setStep(0); };
  return <div className="studio-app"><header className="topbar"><button className="brand" onClick={() => setStep(0)}><span>W</span><strong>Wallpaper AI Studio<small>CONTROLLED PRODUCTION WORKFLOW</small></strong></button><div className="active-project"><span>ACTIVE PROJECT</span><strong>{project.projectName}</strong><small>{RENDER_PROVIDER === "mock" ? "DEVELOPMENT MODE" : "PRODUCTION MODE"}</small></div><nav><a href="https://github.com/berrakorkmaz/wallpaper-ai-studio" target="_blank" rel="noreferrer">GitHub ↗</a><button onClick={newProject}>＋ New project</button></nav></header><div className="app-shell"><aside className="workflow"><div className="workflow-progress"><span>Step {step + 1} of 6</span><b>{progress}% complete</b></div><ol>{steps.map(([number, title, copy], index) => <li key={number} className={index === step ? "active" : states[index]?.complete ? "done" : ""}><button onClick={() => setStep(index)}><span>{states[index]?.complete ? "✓" : number}</span><div><strong>{title}</strong><small>{states[index]?.complete ? states[index].detail : copy}</small></div></button></li>)}</ol><div className="system"><span>SYSTEM</span><p>● User-owned records</p><p>● {RENDER_PROVIDER === "mock" ? "Development renderer" : "Real renderer"}</p><p>● Publish disabled</p></div></aside><main>{step === 0 && <ProductStep project={project} update={update} next={() => setStep(1)} />}{step === 1 && <PromptStep project={project} update={update} next={() => setStep(2)} />}{step === 2 && <DesignStep project={project} update={update} next={() => setStep(3)} />}{step === 3 && <DirectionStep project={project} update={update} next={() => setStep(4)} />}{step === 4 && <RenderStep project={project} update={update} next={() => setStep(5)} />}{step === 5 && <ListingStep project={project} update={update} />}</main><aside className="policy"><span>ASSET POLICY</span><h2>Master locked.</h2><p>Every scene is derived from the approved source through controlled compositing.</p><ul><li>No generative redraw</li><li>Version-linked outputs</li><li>Independent render jobs</li><li>Draft-only marketplace</li></ul><b>MIT LICENSED</b></aside></div></div>;
}
